const TAG = { AD: "ad", TRACKER: "tracker", NATIVE: "native", POPUP: "popup" };

const AD_DOMAINS = [
  "doubleclick.net", "googlesyndication.com", "googleadservices.com",
  "googleads.g.doubleclick.net", "googleadsserving.com", "googletagservices.com",
  "pagead2.googlesyndication.com",
  "taboola.com", "outbrain.com", "revcontent.com", "mgid.com",
  "zemanta.com", "sharethrough.com", "adthrive.com", "mavenpub.com",
  "ezoic.com", "adforge.io",
  "criteo.com", "criteo.net", "crto.net",
  "smartadserver.com", "sascdn.com", "smartclip.net",
  "adform.com", "adform.net", "adkernel.com",
  "indexexchange.com", "openx.net", "openx.com",
  "33across.com", "pubmatic.com",
  "rubiconproject.com", "sonobi.com", "sovrn.com",
  "teads.tv", "undertone.com", "spotx.tv", "spotxchange.com",
  "districtm.net", "yieldmo.com",
  "pubnative.net", "adcolony.com", "inmobi.com",
  "applovin.com", "unityads.unity3d.com", "ironsource.com",
  "hyprmx.com", "supersonicads.com", "adincube.com",
  "ogury.com", "vungle.com", "chartboost.com",
  "mathtag.com", "digitalwindow.com", "cj.com", "cjpxy.com",
  "admitad.com", "affiliatewindow.com",
  "contextweb.com", "realmedia.com", "2o7.net",
  "moatads.com", "integralads.com", "adsafeprotected.com",
  "scorecardresearch.com", "comscore.com", "eyereturn.com",
  "trafficjunky.net", "nanigans.com",
  "adnxs.com", "adsrvr.org", "adsrvr.com",
  "adroll.com", "bttrack.com", "beambox.com",
  "bidswitch.net", "bidr.io", "bidswitch.com",
  "brightroll.com", "yieldlove.com", "videologygroup.com",
  "adserver.com", "adserver.biz",
  "postrelease.com", "adfrontier.com",
  "adskeeper.com", "adrevenue.com",
  "amazon-adsystem.com", "assoc-amazon.com", "media-amazon.com",
  "goxlon.com", "appxdirect.com", "mirtador.com",
  "pushnami.com", "permify.com", "contentad.com", "rcm-na.amazon-adsystem.com",
  "bluekai.com",
  "adsafemedia.com", "adoss.com", "spotx.tv", "adpia.com",
  "imasdk.googleapis.com", "leadboltads.net", "themedia.net",
  "tracker.adform.net", "votes24.com", "rtblp.com", "ak.bid",
  "adzealous.com", "adclickmedia.com", "imadserv.com", "displaymedia.com",
  "netpub.com", "revive.com", "adserverex.com", "targetads.com",
  "advertising.com", "adtech.de", "adscale.de", "adserverplus.com",
  "adpushup.com", "adiquity.com", "adbutler.com", "adglare.com",
  "adversal.com", "adventive.com", "adxcore.com", "adxchange.io",
  "adexchangegateway.com", "adap.tv", "adconion.com", "adedge.com",
  "adlayer.io", "adloo.com", "admaximize.com", "adnami.io",
  "adnative.net", "adorika.com", "adpicker.com", "adpush.com",
  "adquery.io", "adsbridge.com", "adservio.de", "adsido.com",
  "adsimilis.com", "adsitepro.com", "adsot.com", "adspirit.de",
  "adspyglass.com", "adsquare.com", "adsumos.com", "adswizz.com",
  "adsyoda.com", "adtego.com", "adtonos.com", "adtraction.com",
  "adtelligent.com", "adtrade.net", "advertserve.com",
  "advnetwork.net", "adwish.com", "adzhub.com", "aimmatch.com",
  "magnite.com", "triplelift.com", "yieldbot.com", "mediavine.com",
  "gumgum.com", "kanoodle.com", "radiumone.com", "tribalfusion.com",
  "24media.com", "360yield.com", "acuityads.com", "adblade.com",
  "adcade.com", "adlantic.com", "admedia.com", "adsum.net",
  "antvoice.com", "audience2media.com", "burstmedia.com",
  "clickdistrict.com", "conversantmedia.com", "cpvfeed.com",
  "emxdgt.com", "epsilon.com", "eplanning.net", "futureads.com",
  "geniee.co.jp", "hubvisor.io", "justpremium.com", "kwanko.com",
  "lifestreet.com", "lockerdome.com", "medianet.com", "microad.jp",
  "millennialmedia.com", "mobfox.com", "mopub.com", "nativo.com",
  "netseer.com", "perion.com", "pulsepoint.com", "realcast.io",
  "relap.io", "rtbmarket.com", "runative.com", "sekindo.com",
  "smaato.com", "sociomantic.com", "springserve.com", "stackadapt.com",
  "tappx.com", "towerdata.com", "vlix.io", "vrtcal.com",
  "widespace.com", "xad.com", "ads.yahoo.com", "advertising.jp",
  "beeswax.io", "adnxsair.com", "adnxs.net"
];

const TRACKER_DOMAINS = [
  "connect.facebook.net", "graph.facebook.com", "analytics.tiktok.com",
  "ads.tiktok.com", "analytics.snapchat.com", "scdn.co",
  "amplitude.com", "segment.io", "segment.com",
  "tealium.com", "ensighten.com",
  "fullstory.com", "hotjar.com", "mouseflow.com",
  "luckyorange.com", "newrelic.com", "nr-data.net",
  "bugsnag.com", "sentry.io", "datadog.com",
  "logrocket.com", "clarity.ms",
  "optimizely.com", "vwo.com",
  "qualtrics.com", "medallia.com", "qualaroo.com",
  "branch.io", "appsflyer.com", "adjust.com", "kochava.com",
  "mixpanel.com", "heap.io",
  "krxd.net", "demdex.net", "audience.com",
  "lotame.com", "msads.net",
  "tapad.com", "yx-deriv.com", "orbengine.com",
  "gemius.pl", "yieldlab.de",
  "chartbeat.com", "quantcount.com", "quantserve.com",
  "snap.com/measurement",
  "flurry.com", "flurry.yahoo.com",
  "foxmetrics.com", "gigya.com", "kissmetrics.com", "matomo.cloud",
  "navilytics.com", "nielsen.com", "omtrdc.net", "parsely.com",
  "shareaholic.com", "siteimprove.com", "smartlook.com",
  "toutapp.com", "userreplay.com", "visualwebsiteoptimizer.com",
  "webtrekk.com", "mc.yandex.ru", "cdn.privacy-mgmt.com",
  "experience.dyn.cn", "intercomcdn.com/intercom/assets",
  "2mdn.net", "static.doubleclick.net", "adservice.google.com/adsense",
  "ad.mob", "sifo.doubleclick.net", "sdk4.inmobi.com",
  "graphs.ns8.com", "bam.nr-data.net", "js-agent.newrelic.com",
  "foresee.com", "heapanalytics.com", "indicative.com",
  "getsitecontrol.com", "olark.com", "drift.com", "intercom.io",
  "zendesk.com/widgets", "tawk.to", "crisp.chat", "livechatinc.com",
  "hotjaruser.com", "sessioncam.com", "inspectlet.com",
  "crazyegg.com", "quantified.ai", "audienceinsights.net"
];

const NATIVE_DOMAINS = [
  "taboola.com", "outbrain.com", "revcontent.com", "mgid.com",
  "zemanta.com", "sharethrough.com", "adthrive.com", "mavenpub.com",
  "reservoirads.com", "unrulymedia.com", "semasio.com",
  "clairant.com", "contentad.co", "contentamp.com",
  "rhythmone.com", "tvmobili.com", "zoutindy.com"
];

const POPUP_DOMAINS = [
  "popunder.io", "popmine.com", "gppmix.com",
  "gatewaycorridor.com", "pillowtime.pro", "milkymesa.info",
  "bitumbral.com", "newpushr.com", "opennauds.com",
  "nosomw.com", "columnistyr.com", "weboutcome.com",
  "portlylane.cc", "delivernamethat.com", "purifycap.com",
  "regionsupel.com", "instreamsdk.com", "papertreecurve.icu",
  "flifan.com", "bleakorigins.fun", "koirai.net", "5trot.com",
  "popads.net", "popcash.net", "popunder.com", "adsterra.com",
  "propellerads.com", "evadav.com", "trafficstars.com",
  "propellerclick.com", "onclickpredict.com",
  "popub.com", "4dsply.com",
  "moonlighthathel.org", "viinyzfu.com", "radiancerelaysacred.com",
  "beadpie.xyz", "runoperagx.com", "rdozone.com", "adbucks.top",
  "qxbroker.com", "qbxbroker.com", "playin04.com", "gohappyin.com",
  "sc.woughbitis.shop", "woughbitis.shop", "xlynq.com", "1xlite-12947.pro",
  "1xbetmirror.site", "knuwlog.com"
];

const AD_PATH_PATTERNS = [
  /\/adsbygoogle\.js(\?|#|$)/i,
  /\/pagead\/js\/adsbygoogle\.js/i,
  /\/googletagmanager\.com\/gtag\/js/i,
  /\/googletagmanager\.com\/gtm\.js/i,
  /(^|\/)ads\/ads\.js/i
];

module.exports = { TAG, AD_DOMAINS, TRACKER_DOMAINS, NATIVE_DOMAINS, POPUP_DOMAINS, AD_PATH_PATTERNS };